$ANSIBLE_VAULT;1.1;AES256
30326632396439353461303535383539343237366264326436643037666234373566626563396262
3465376630353438656235626363393466353934663064390a393764626161626631333537353732
37316133373266643234386232623739646463356366396266616161663465623231353733383739
6438636531356631660a326334326138393164383335626165373837616664363364333835343338
66633934386536663934356533393363396263623039633938613333363462633135343034373765
66343861373038306538323263623162633465623837363938303232393264636366373839323130
66316564396438386431333237653764303935363939396563303536633936333064343430643264
65333131356435633734386365656666333566636166373234633932646533343632353839353162
6662
